import { Platform } from 'react-native';

/**
 * Build the complete style sheet for the app.
 * @param {object} palette - color palette object (dark or light theme)
 */
export function makeStyles(palette) {
  return {
    // ---------- Root / Layout ----------
    safeArea: {
      flex: 1,
      backgroundColor: palette.page,
    },
    container: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: Platform.OS === 'android' ? 64 : 32,
    },
    topSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 16,
      marginBottom: 36,
    },
    smallLabel: {
      color: palette.muted,
      fontSize: 12,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 12,
    },
    mainTitle: {
      color: palette.text,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: 1.5,
      marginTop: 0,
    },
    themeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: palette.panel,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    themeButtonText: {
      fontSize: 18,
    },
    cityRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    locationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    locationName: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginTop: 2,
    },
    locationButton: {
      backgroundColor: palette.panel,
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    locationButtonText: {
      color: palette.primary,
      fontSize: 12,
      fontWeight: '700',
    },
    locationErrorText: {
      color: '#e05d5d',
      fontSize: 11,
      marginTop: 4,
    },
    videoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    playBadge: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#FF4E45',
      alignItems: 'center',
      justifyContent: 'center',
    },
    playBadgeText: {
      color: '#ffffff',
      fontSize: 13,
      marginLeft: 2,
    },
    channelLink: {
      alignSelf: 'flex-end',
      marginTop: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    channelLinkText: {
      color: palette.primary,
      fontSize: 11,
      fontWeight: '700',
    },
    fallbackButton: {
      marginTop: 8,
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: palette.panel,
      borderWidth: 1,
      borderColor: palette.border,
    },
    fallbackButtonText: {
      color: palette.muted,
      fontSize: 12,
      fontWeight: '600',
    },
    cityText: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    timeText: {
      color: palette.muted,
      fontSize: 14,
      fontVariant: ['tabular-nums'],
    },
    tabRow: {
      flexDirection: 'row',
      backgroundColor: palette.panel,
      borderRadius: 12,
      padding: 4,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    tab: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 8,
      alignItems: 'center',
    },
    tabActive: {
      backgroundColor: palette.primary,
    },
    tabText: {
      color: palette.muted,
      fontSize: 12,
      fontWeight: '600',
    },
    tabTextActive: {
      color: '#08131a',
      fontWeight: '700',
    },

    // ---------- Shared content ----------
    contentPadding: {
      paddingBottom: 24,
    },
    card: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    cardTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 10,
    },
    cardLabel: {
      color: palette.muted,
      fontSize: 13,
      marginBottom: 4,
    },
    sectionTag: {
      color: palette.primary,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 8,
    },
    sectionHeading: {
      color: palette.text,
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 12,
    },
    input: {
      backgroundColor: palette.panel,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: palette.text,
      fontSize: 14,
      marginBottom: 10,
    },
    label: {
      color: palette.muted,
      fontSize: 13,
      marginBottom: 6,
      fontWeight: '600',
    },
    primaryButton: {
      backgroundColor: palette.primary,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
      marginTop: 8,
    },
    primaryButtonText: {
      color: '#08131a',
      fontSize: 15,
      fontWeight: '700',
    },
    button: {
      backgroundColor: palette.primary,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      alignItems: 'center',
      alignSelf: 'flex-start',
    },
    buttonText: {
      color: '#08131a',
      fontSize: 14,
      fontWeight: '700',
    },
    disabledButton: {
      opacity: 0.5,
    },

    // ---------- Auth Screen ----------
    authScreen: {
      flex: 1,
      backgroundColor: palette.page,
      justifyContent: 'center',
      paddingHorizontal: 20,
    },
    authCard: {
      backgroundColor: palette.card,
      borderRadius: 20,
      padding: 24,
      borderWidth: 1,
      borderColor: palette.border,
    },
    logoCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: palette.soft,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginBottom: 12,
    },
    welcomeLabel: {
      color: palette.muted,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 4,
    },
    appTitle: {
      color: palette.text,
      fontSize: 24,
      fontWeight: '800',
      textAlign: 'center',
      letterSpacing: 1.5,
      marginBottom: 8,
    },
    subtitle: {
      color: palette.muted,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 6,
    },
    communityNote: {
      color: palette.accent,
      fontSize: 12,
      textAlign: 'center',
      marginBottom: 16,
    },
    authToggleRow: {
      flexDirection: 'row',
      backgroundColor: palette.panel,
      borderRadius: 10,
      padding: 4,
      marginBottom: 16,
    },
    authModeButton: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 8,
      alignItems: 'center',
    },
    authModeButtonActive: {
      backgroundColor: palette.primary,
    },
    authModeText: {
      color: palette.muted,
      fontSize: 14,
      fontWeight: '600',
    },
    authModeTextActive: {
      color: '#08131a',
      fontWeight: '700',
    },
    formBox: {
      marginTop: 4,
    },
    securityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    securityIcon: {
      color: palette.accent,
      fontSize: 14,
      marginRight: 6,
    },
    securityText: {
      color: palette.muted,
      fontSize: 12,
    },
    dividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 16,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: palette.border,
    },
    dividerText: {
      color: palette.muted,
      fontSize: 12,
      marginHorizontal: 10,
    },
    googleButton: {
      backgroundColor: palette.panel,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    googleButtonText: {
      fontSize: 14,
      fontWeight: '600',
    },
    googleBlue: { color: '#4285F4' },
    googleRed: { color: '#EA4335' },
    googleYellow: { color: '#FBBC05' },
    googleGreen: { color: '#34A853' },
    googleText: { color: palette.text },

    // ---------- Prayer Tab ----------
    clearRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    primaryPrayer: {
      color: palette.text,
      fontSize: 28,
      fontWeight: '800',
      fontVariant: ['tabular-nums'],
    },
    rightAligned: {
      alignItems: 'flex-end',
    },
    timerText: {
      color: palette.primary,
      fontSize: 20,
      fontWeight: '700',
      fontVariant: ['tabular-nums'],
    },
    listWrap: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    rowItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 8,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    leftGroup: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    dot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: palette.border,
      marginRight: 10,
    },
    dotActive: {
      backgroundColor: palette.primary,
    },
    rowLabel: {
      color: palette.text,
      fontSize: 14,
      fontWeight: '500',
    },
    rowTime: {
      color: palette.muted,
      fontSize: 14,
      fontVariant: ['tabular-nums'],
    },

    // ---------- Q&A Tab ----------
    essayCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: palette.border,
    },
    qRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    sparkDot: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: palette.soft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    sparkText: {
      color: palette.primary,
      fontSize: 12,
    },
    qText: {
      flex: 1,
      color: palette.text,
      fontSize: 14,
      fontWeight: '600',
    },
    expandText: {
      color: palette.muted,
      fontSize: 18,
      marginLeft: 8,
    },
    answerWrap: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    answerText: {
      color: palette.muted,
      fontSize: 13,
      lineHeight: 20,
    },
    referenceButton: {
      marginTop: 10,
      alignSelf: 'flex-start',
    },
    referenceButtonText: {
      color: palette.accent,
      fontSize: 12,
      textDecorationLine: 'underline',
    },
    // Q&A new styles
    qaAskCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    qaAskTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 10,
    },
    qaMostAskedSection: {
      marginBottom: 12,
    },
    qaMostAskedTitle: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 8,
    },
    qaMostAskedCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: palette.primary,
    },
    qaMostAskedBadge: {
      color: palette.primary,
      fontSize: 11,
      fontWeight: '700',
      marginBottom: 6,
    },
    qaAllQuestionsTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 10,
      marginTop: 4,
    },
    qaLikesRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    qaLikeButton: {
      color: palette.accent,
      fontSize: 13,
      fontWeight: '600',
      marginRight: 12,
    },
    qaLikeButtonLiked: {
      color: palette.primary,
    },
    qaAnswerCount: {
      color: palette.muted,
      fontSize: 12,
    },
    qaAnswersSection: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    qaAnswerItem: {
      backgroundColor: palette.cardSoft,
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
    },
    qaAnswerHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    qaAnswerAvatar: {
      fontSize: 18,
      marginRight: 8,
    },
    qaAnswerUser: {
      color: palette.text,
      fontSize: 13,
      fontWeight: '600',
    },
    qaAnswerTime: {
      color: palette.muted,
      fontSize: 11,
    },
    qaAnswerText: {
      color: palette.text,
      fontSize: 13,
      lineHeight: 19,
      marginBottom: 6,
    },
    qaAnswerFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    qaAnswerLike: {
      color: palette.accent,
      fontSize: 12,
    },
    qaAnswerLikeLiked: {
      color: palette.primary,
    },
    qaNoAnswers: {
      color: palette.muted,
      fontSize: 12,
      fontStyle: 'italic',
      marginBottom: 8,
    },
    qaAnswerInput: {
      backgroundColor: palette.panel,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: palette.text,
      fontSize: 13,
      marginBottom: 8,
      minHeight: 60,
      textAlignVertical: 'top',
    },
    qaAnswerSubmit: {
      backgroundColor: palette.primary,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 14,
      alignItems: 'center',
      alignSelf: 'flex-start',
    },
    qaAnswerSubmitText: {
      color: '#08131a',
      fontSize: 13,
      fontWeight: '700',
    },
    qaAddAnswerButton: {
      marginTop: 8,
      alignSelf: 'flex-start',
    },
    qaAddAnswerButtonText: {
      color: palette.accent,
      fontSize: 13,
      fontWeight: '600',
    },
    qaAnswerForm: {
      marginTop: 8,
    },
    qaEmptyState: {
      color: palette.muted,
      fontSize: 13,
      textAlign: 'center',
      paddingVertical: 20,
    },

    // ---------- News Tab ----------
    eventBlock: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: palette.border,
    },
    versionHeader: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 8,
    },
    notesList: {
      marginTop: 4,
    },
    note: {
      color: palette.muted,
      fontSize: 13,
      lineHeight: 20,
      marginBottom: 4,
    },

    // ---------- Community Tab ----------
    tabContent: {
      flex: 1,
    },
    postHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    avatar: {
      fontSize: 24,
      marginRight: 10,
    },
    postUser: {
      color: palette.text,
      fontSize: 14,
      fontWeight: '600',
    },
    postTime: {
      color: palette.muted,
      fontSize: 12,
    },
    postQuestion: {
      color: palette.text,
      fontSize: 15,
      fontWeight: '600',
      marginBottom: 8,
    },
    contributionCount: {
      color: palette.muted,
      fontSize: 12,
      marginBottom: 8,
    },
    contribution: {
      backgroundColor: palette.cardSoft,
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
    },
    contributionText: {
      color: palette.text,
      fontSize: 13,
      lineHeight: 19,
      marginBottom: 6,
    },
    contributionFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    likeButton: {
      color: palette.accent,
      fontSize: 13,
    },
    addContribution: {
      marginTop: 8,
    },
    aiAnswerButton: {
      marginTop: 8,
      marginBottom: 4,
      backgroundColor: palette.soft,
      borderWidth: 1,
      borderColor: palette.primary,
      alignSelf: 'stretch',
    },
    aiAnswerButtonText: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '700',
    },
    aiAnswerLoadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    aiErrorText: {
      color: '#e05d5d',
      fontSize: 12,
      marginTop: 4,
      marginBottom: 4,
    },
    aiContribution: {
      backgroundColor: palette.soft,
      borderWidth: 1,
      borderColor: palette.primary,
    },
    aiBadgeWrap: {
      alignItems: 'flex-end',
      marginTop: 4,
      marginBottom: 4,
    },
    aiBadge: {
      color: palette.primary,
      fontSize: 11,
      fontWeight: '700',
      backgroundColor: palette.panel,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      overflow: 'hidden',
    },
    // Community new styles
    communityCreateCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    communityCreateTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 10,
    },
    communityPostInput: {
      backgroundColor: palette.panel,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: palette.text,
      fontSize: 14,
      marginBottom: 10,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    communityMediaRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 10,
    },
    communityMediaButton: {
      backgroundColor: palette.panel,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    communityMediaButtonText: {
      color: palette.text,
      fontSize: 12,
      fontWeight: '600',
    },
    communityMediaPreview: {
      marginBottom: 10,
    },
    communityMediaImage: {
      width: '100%',
      height: 200,
      borderRadius: 10,
    },
    communityMediaVideo: {
      width: '100%',
      height: 200,
      borderRadius: 10,
    },
    communityMediaRemove: {
      color: '#e05d5d',
      fontSize: 12,
      fontWeight: '600',
      marginTop: 6,
    },
    communityShareButton: {
      backgroundColor: palette.primary,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      alignItems: 'center',
      alignSelf: 'flex-start',
    },
    communityShareButtonText: {
      color: '#08131a',
      fontSize: 14,
      fontWeight: '700',
    },
    communityPostText: {
      color: palette.text,
      fontSize: 15,
      lineHeight: 21,
      marginBottom: 8,
    },
    communityPostMedia: {
      marginBottom: 8,
    },
    communityPostImage: {
      width: '100%',
      height: 220,
      borderRadius: 10,
    },
    communityPostVideo: {
      width: '100%',
      height: 220,
      borderRadius: 10,
    },
    communityPostActions: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    communityPostLike: {
      color: palette.accent,
      fontSize: 13,
      fontWeight: '600',
      marginRight: 16,
    },
    communityPostLikeLiked: {
      color: palette.primary,
    },
    communityPostCommentCount: {
      color: palette.muted,
      fontSize: 13,
    },
    communityCommentsSection: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    communityCommentItem: {
      backgroundColor: palette.cardSoft,
      borderRadius: 10,
      padding: 10,
      marginBottom: 8,
    },
    communityCommentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    communityCommentAvatar: {
      fontSize: 16,
      marginRight: 8,
    },
    communityCommentUser: {
      color: palette.text,
      fontSize: 12,
      fontWeight: '600',
    },
    communityCommentTime: {
      color: palette.muted,
      fontSize: 11,
    },
    communityCommentText: {
      color: palette.text,
      fontSize: 13,
      lineHeight: 18,
      marginBottom: 4,
    },
    communityCommentFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    communityCommentLike: {
      color: palette.accent,
      fontSize: 12,
    },
    communityCommentLikeLiked: {
      color: palette.primary,
    },
    communityNoComments: {
      color: palette.muted,
      fontSize: 12,
      fontStyle: 'italic',
      marginBottom: 8,
    },
    communityCommentInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    communityCommentInput: {
      flex: 1,
      backgroundColor: palette.panel,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: palette.text,
      fontSize: 13,
    },
    communityCommentSubmit: {
      backgroundColor: palette.primary,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      alignItems: 'center',
    },
    communityCommentSubmitText: {
      color: '#08131a',
      fontSize: 12,
      fontWeight: '700',
    },
    communityMediaBadge: {
      color: palette.muted,
      fontSize: 11,
      fontWeight: '600',
      marginBottom: 4,
    },

    // ---------- Settings Tab ----------
    settingCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    settingHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    settingTitle: {
      color: palette.text,
      fontSize: 15,
      fontWeight: '700',
    },
    settingValue: {
      color: palette.muted,
      fontSize: 12,
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 8,
    },
    modeButton: {
      flex: 1,
      backgroundColor: palette.panel,
      borderRadius: 8,
      paddingVertical: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    modeButtonActive: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    modeButtonText: {
      color: palette.text,
      fontSize: 13,
      fontWeight: '600',
    },
    soundList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    soundItem: {
      backgroundColor: palette.panel,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    soundItemActive: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    soundText: {
      color: palette.text,
      fontSize: 12,
    },
    accountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    accountIcon: {
      fontSize: 24,
      marginRight: 10,
    },
    accountName: {
      color: palette.muted,
      fontSize: 13,
      marginTop: 2,
    },
    logoutButtonText: {
      color: '#e05d5d',
      fontSize: 13,
      fontWeight: '600',
    },
    settingRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    settingRowText: {
      color: palette.text,
      fontSize: 14,
    },
    arrow: {
      color: palette.muted,
      fontSize: 18,
    },

    // ---------- Settings Modals ----------
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.55)',
      justifyContent: 'center',
      padding: 20,
    },
    modalCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 20,
      borderWidth: 1,
      borderColor: palette.border,
      width: '100%',
    },
    modalTitle: {
      color: palette.text,
      fontSize: 17,
      fontWeight: '700',
      marginBottom: 16,
    },
    modalMessage: {
      color: palette.muted,
      fontSize: 13,
      marginBottom: 16,
      lineHeight: 20,
    },
    modalButtonRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 8,
    },
    modalButton: {
      flex: 1,
      backgroundColor: palette.primary,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
    },
    modalButtonText: {
      color: '#08131a',
      fontSize: 15,
      fontWeight: '700',
    },
    modalCancelButton: {
      flex: 1,
      backgroundColor: palette.panel,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    modalCancelButtonText: {
      color: palette.text,
      fontSize: 15,
      fontWeight: '600',
    },
    modalError: {
      color: '#e05d5d',
      fontSize: 13,
      marginBottom: 10,
    },
    passwordRequirement: {
      color: palette.muted,
      fontSize: 12,
      marginBottom: 10,
    },

    // ---------- Profile Setup ----------
    setupCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 20,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    bioInput: {
      minHeight: 80,
      textAlignVertical: 'top',
    },
    profilePictureButton: {
      alignSelf: 'center',
      marginBottom: 8,
    },
    profilePicture: {
      width: 96,
      height: 96,
      borderRadius: 48,
      borderWidth: 2,
      borderColor: palette.primary,
    },
    profilePicturePlaceholder: {
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: palette.soft,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: palette.border,
    },
    profilePicturePlaceholderText: {
      fontSize: 32,
    },
    profilePictureHint: {
      color: palette.muted,
      fontSize: 12,
      textAlign: 'center',
      marginBottom: 12,
    },

    // ---------- Welcome Screen ----------
    welcomeCard: {
      backgroundColor: palette.card,
      borderRadius: 20,
      padding: 24,
      borderWidth: 1,
      borderColor: palette.border,
    },
    welcomeGreeting: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'center',
      marginBottom: 6,
    },
    welcomeTimeGreeting: {
      color: palette.text,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 12,
    },
    welcomeText: {
      color: palette.muted,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      marginBottom: 16,
    },
    featureHighlight: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.soft,
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
    },
    featureIcon: {
      fontSize: 18,
      marginRight: 10,
    },
    featureText: {
      color: palette.text,
      fontSize: 13,
      flex: 1,
    },
  };
}